---
  - name: "Display content of file root_cronjob_monitoring_sysstat.txt"
    hosts: localhost
    tasks:
    - name: ping test
      ping:

    - name: Get root_cronjob_monitoring_sysstat.txt contents
      command: cat root_cronjob_monitoring_sysstat.txt chdir=/vagrant
      register: command_output

    - name: Print to console
      debug:
        msg: "{{command_output.stdout}}"

    - name: "find files in /vagrant"
      find:
        paths: '/vagrant'
